name: CI
on: [pull_request]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v2
      - run: yarn install

      - run: npx nx format:check --base=main --head=HEAD
      - run: npx nx affected --target=lint --base=main --head=HEAD
      - run: npx nx affected --target=test--ci --code-coverage --base=main --head=HEAD
      - run: npx nx affected --target=build --parallel=3 --base=main --head=HEAD
      - run: npx nx affected --target=e2e --base=main --head=HEAD
